dist: trusty
sudo: false
language: generic

branches:
  only:
    - testing

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libeigen3-dev
            - libboost-test-dev
      env: COMPILER=gcc CC=gcc CXX=g++

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libstdc++-4.9-dev
            - libeigen3-dev
            - libboost-test-dev
      env: COMPILER=gcc CC=gcc-4.9 CXX=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libstdc++-5-dev
            - libeigen3-dev
            - libboost-test-dev
      env: COMPILER=gcc CC=gcc-5 CXX=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libstdc++-6-dev
            - libeigen3-dev
            - libboost-test-dev
      env: COMPILER=gcc CC=gcc-6 CXX=g++-6

    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libeigen3-dev
            - libboost-test-dev
      env: COMPILER=clang CC=clang CXX=clang++

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libeigen3-dev
            - libboost-test-dev
      env: COMPILER=clang CC=clang-3.9 CXX=clang++-3.9

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libeigen3-dev
            - libboost-test-dev
      env: COMPILER=clang CC=clang-4.0 CXX=clang++-4.0

script:
  - mkdir cmake
  - ln -s /usr/share/cmake-2.8/Modules/FindEigen3.cmake cmake/
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
